### ISSUE TITLE
confusion about self_pipe

### ISSUE THREAD

**Issue by wTuo** [Cylix/tacopie#12]
I've read your code carefully recent days,learning your program skills.  But I'm confused about the role of self_pipe in class io_service. How does it work?

**Comment by Cylix** [comment]
Hi,

Thanks for your interest in `tacopie` :)

The purpose of the self_pipe is to wake up the select polling call.

Indeed, in the `io_service`, I call `select()` (for example, [here](https://github.com/Cylix/tacopie/blob/master/sources/network/unix/io_service.cpp#L91)).
`select` will poll the given file descriptors (fds) sets for reading and writing events and will wake up whenever an event occurs (socket is readable or writable) or whenever the given timeout has expired.

However, I decided to set a NULL timeout when calling `select`.
From the documentation `If timeout is a nil pointer, the select blocks indefinitely.`.

What is the benefit of setting an unlimited timeout?
Well, first it saves some CPU usage: if no event occurs during 5mn, your program will stay inactive during these 5mn without consuming any CPU power.
Second, if you want to modify the fd sets, you don't need to wait for the timeout to expire so that it refresh the list of sockets to poll. This can be a real struggle because if you set a too low timeout, your program will consume a lot the CPU for nothing 99% of the time, but if you set a too high timeout, then your program might be a bit slow to listen to read or write availability when we want to poll a new socket.

But if we have an unlimited timeout, this means that our select only wakes up if a socket is available for reading or writing!
So what if we want to poll a new socket? What if we want to stop polling one socket?
We need to be able to wake up the select call instantly.

One way to do it is mostly to use the `self-pipe trick`.
The principle is simple:

* you create a pipe
* you listen for read availability on one side of the pipe
* when you want to wake your select call, you write on the other side of the pipe
* magic: select wakes up and notify you that the first side of the select has some bytes that can be read!

You can see that basically, I use the self-pipe trick anytime I need to wake-up select due to some external changes:
* [when I want to turn off the io_service](https://github.com/Cylix/tacopie/blob/master/sources/network/unix/io_service.cpp#L91)
* [when I complete the execution of a read/write callback](https://github.com/Cylix/tacopie/blob/master/sources/network/unix/io_service.cpp#L160) (indeed, some actions done in the callback might have modified the state of the socket, like doing async_read, async_write or simply disconnect: we need to wake up select to reflect these changes).
* [whenever I track/untrack a socket or listen to new types of event](https://github.com/Cylix/tacopie/blob/master/sources/network/unix/io_service.cpp#L241)

Hope this makes the `self-pipe` part of the code more clear for you :)

Do not hesitate to let me know if you have any other questions.

Best!
