### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by dhirst2880** [Cylix/tacopie#14]
[io_service_diff.txt](https://github.com/Cylix/tacopie/files/1069171/io_service_diff.txt)

I'm using tacopie as part of the cpp_redis library. I'm seeing extremely high CPU usage (nearly 100%) on a system that is not making any calls to the redis server. 

The root cause seems to be in the use of self_pipe in the io_service. The two uses of self_pipe that I don't understand are on io_service.cpp:160. In this instance you always notify the pipe that it should wake up, but it seems like the pipe should only be woken up if the state of the socket changed (in other words m_notifier.notify(), should be moved inside to io_service.cpp:158 (inside the if block). I don't see similar usage inside process_wr_event, and I'm wondering why that's the case. 

The other usage of self_pipe that I don't understand is in the process_events() function (io_service.cpp:130). Could you help me understand why the pipe needs to be written to at the end of this function? 

I uploaded a patch I think might help resolve the high CPU usage.

Thanks!
-DH

**Comment by Cylix** [comment]
Hi,

Thanks for opening this issue and for your analysis!

This issue is related to the 2 issues opened on cpp_redis:
* [cpp_redis#75](https://github.com/Cylix/cpp_redis/issues/75)
* [cpp_redis#77](https://github.com/Cylix/cpp_redis/issues/77)

A few week ago I started to dig into it and I also found these 2 and couldn't remember the reason they were there (especially the process_rd one considering there is not even any in the process_wr one.).
I didn't had the time to dig more until now but I'm planning to solve it by the end of the week at the latest.

I also have to investigate CPU usage on mono-core systems but got some issues with my VMWare (license expired), so might delay a bit. So I guess I'll do the first fix and then investigate more on mono-core system (though the fix might be the same).

Best!

**Comment by Cylix** [comment]
Hi,

I just released version `2.4.3`.
I applied a fix concerning the unnecessary use of self-pipe and I hope this will help to solve the issue (I basically removed the 

I also included a way to configure the timeout of select just in case by using the CMake variable SELECT_TIMEOUT (documentation has been updated to include this new variable).

I made some tests on my macbook (8 cores) and on a virtual machine (debian - 1 core), but on both I got low CPU usage before the fix when changing the `cpp_redis` example (basically, the provided one does a while (!should_stop){} that obviously consumes 100% of a core, but when switching to a signaling condvar, CPU usage is really low).
So it is pretty hard for me to see if the fix is efficient.

Keep me up to date if you happen to test it, I would really appreciate :)
Otherwise, I'll close the issue in a few weeks in the absence of any response, the time to see if anyone complains again concerning CPU usage or not.

Best!
