### ISSUE TITLE
BAD

### ISSUE THREAD

**Issue by intgogo** [Cylix/tacopie#37]
This is really a very good library if you remove the usage of c++ exception!!!!!!VERY BAD DESIGN

================================
terminate called after throwing an instance of 'tacopie::tacopie_error'
  what():  getaddrinfo() failure
Press <RETURN> to close this window...
================================

See...My app crashed just because I didn't use 'try...catch...'
If you follow Microsoft, you will dead in the end!

**Comment by Cylix** [comment]
Hi,

Sorry that you encounter issues while using tacopie.

Unfortunately, I do not plan to change anything concerning exceptions.
Exceptions are extremely powerful for multiple reasons:

* from a code point of view, it makes the implementation clearer by avoiding to use error codes returned by functions and to keep propagate these error codes (sometimes losing their meaning because the return type is incompatible) and allowing to fully take advantage of the return value as a successful return value at any case while exception is raised in case of error
* from a library point of view, it allows to pass tons of different additional information concerning the error, not just an error code. This information can help for logging, troubleshooting or in the decision process of what should be done when this failure happens.
* from a user point of view, it enforces that you do not ignore errors that may be critical. You must explicitly ignore an exception, but at least you know that something bad can happen and determined that you do not want to take any action despite the failure.
* from a user point of view, it makes error handling much better by allowing to grab all exception at once and have a global error handling, or to implement fine-grain error handling based on exception type (several catches for each different type of exception).

Also, back in the time, the main downside of exception was the potential decrease in performance. This is not true anymore in recent C++ version.

In the particular case you encountered, an exception is perfectly justified. getaddrinfo failed to process, which means that the host you specified is invalid or that you have some network-related issues. In any case, the connection has failed and your client needs to take action: is it a critical error and my program need to exit? Is it not critical and then my program can process further? If so, how?

I'm closing this issue as nothing will be changed concerning exceptions and there is no bug apparently.

However, do not hesitate to reply if you want to discuss more concerning this topic and you are free to open another issue if you encounter any problem while using tacopie.

Best,
