### ISSUE TITLE
tacopie::tcp_client::async_read returning before reading all bytes

### ISSUE THREAD

**Issue by Epidal** [Cylix/tacopie#8]
The documentation for `tacopie::tcp_client::write_request` implies that `tacopie::tcp_client::async_read()` calls the callback after reading a user-defined number of bytes from the network stream, but this is not the case.  It will read AT MOST `write_request.size` bytes.  The callback will be invoked even if a lesser number of bytes have been read.  I'm not sure if this is how it's supposed to work or not, but it makes reading length-prefixed messages a little more complicated (ie. I don't really want to have to resort to using an awkward callback loop, or just directly using the tcp_client's socket)

**Comment by Cylix** [comment]
Hi,

Your observations are correct and this is an expected behavior.
The `async_read` (as well as the `async_write`) acts as a request: it asks to read x bytes, but there is no guarantee it does.
Thus, you have to check if the `read_result` (or `write_result`) reports that it read (or wrote) the requested number of bytes. It is then up to you to start a new request and to merge the packets together.

I don't really plan to change this behavior as some other people will expect this current behavior to have more control on what is happening.

I have updated the documentation to make it more clear as it can be confusing indeed.

Please let me know if you have any other questions!

Best :)

**Comment by Cylix** [comment]
Closing this issue.
Please feel free to re-open it if necessary.

Best
